Judgmentrac/Controllers/CommerceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Security.Cryptography;
using System.Text;
using WebMatrix.WebData;
using Judgmentrac.Models;

namespace Judgmentrac.Controllers
{
    public class CommerceController : Controller
    {

        #region Helper Methods
        private string ByteToString(byte[] buff)
        {
            string sbinary = "";

            for (int i = 0; i < buff.Length; i++)
            {
                sbinary += buff[i].ToString("X2"); // hex format
            }
            return (sbinary);
        }

        private bool DeleteInvoice(int invoiceID)
        {
            try
            {
                JudgmentDB db = new JudgmentDB();
                UserProfileJudgment invoice = db.UserProfileJudgments.Find(invoiceID);
                db.UserProfileJudgments.Remove(invoice);
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }

        private bool UpdateInvoice(int invoiceID, int numJudgments)
        {
            try
            {
                JudgmentDB db = new JudgmentDB();
                UserProfileJudgment invoice = db.UserProfileJudgments.Find(invoiceID);
                invoice.JudgmentCount = numJudgments;
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }
        #endregion

        // GET: /Commerce/
        [Authorize]
        public ActionResult Index()
        {
            string amount = ConfigurationManager.AppSettings["JudgmentAmount"];
            ViewBag.TotalPrice = amount;

            return View();
        }


        // GET: /Commerce/Purchase
        [Authorize]
        [HttpPost]
        public ActionResult Purchase(FormCollection postData)
        {
            string apiLoginID = ConfigurationManager.AppSettings["AuthorizeAPILoginID"];
            
            // get amount of purchase
            string amount = postData["x_amount"];
            ViewBag.Amount = amount;
            ViewBag.NumJudgment = postData["num_judgment"];

            // Invoice: create a new UserProfileJudgment record that will become the invoice (after we hear back from Authorize.NET)
            int invoice = 0;
            using (var judgment = new JudgmentDB())
            {
                UserProfileJudgment userProfileJudgment = new UserProfileJudgment
                {
                    UserId = WebSecurity.CurrentUserId,
                    JudgmentCount = 0
                };
                judgment.UserProfileJudgments.Add(userProfileJudgment);
                if (judgment.SaveChanges() == 1)
                    invoice = userProfileJudgment.invoice;
            }
            ViewBag.Invoice = invoice.ToString();

            // generate timestamp for Authorize.NET
            //string totalSeconds = (DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds.ToString();
            //string secondsRounded = totalSeconds.Substring(0, totalSeconds.IndexOf("."));
            //ViewBag.Seconds = secondsRounded;
            ViewBag.Seconds = AuthorizeNet.Crypto.GenerateTimestamp();

            /* Authorize.NET SDK methods to help with the direct post method (but not much documentation)
            AuthorizeNet.Crypto.GenerateSequence();
            AuthorizeNet.Crypto.GenerateFingerprint();
            */

            string hashSeed = apiLoginID + "^" + invoice + "^" + ViewBag.Seconds + "^" + amount + "^";
            string hashKey = ConfigurationManager.AppSettings["AuthorizeTransactionKey"];

            ASCIIEncoding encoding = new ASCIIEncoding();
            byte[] keyByte = encoding.GetBytes(hashKey);
            HMACMD5 hmacmd5 = new HMACMD5(keyByte);
            byte[] messageBytes = encoding.GetBytes(hashSeed);
            byte[] hashmessage = hmacmd5.ComputeHash(messageBytes);
            ViewBag.MD5Hash = ByteToString(hashmessage);

            return View();
        }


        [HttpPost]
        public ActionResult DPM(FormCollection post)
        {
            var response = new AuthorizeNet.SIMResponse(post);

            //validate that it was Auth.net that posted this using the first 20 characters of the "MD5 hash" string specifiec in the settins admin pannel
            bool isValid = response.Validate(ConfigurationManager.AppSettings["AuthorizeMerchantHash"], ConfigurationManager.AppSettings["AuthorizeAPILoginID"]);

            //foreach (string key in post.Keys)
            //    ViewBag.Message += "Key: " + key + "<br>";

            //ViewBag.Message = "Is Response Valid? " + isValid.ToString() +
            //    ", Message: " + response.Message +
            //    ", Invoice: " + response.InvoiceNumber +
            //    ", ResponseCode: " + response.ResponseCode +
            //    ", MD5Hash: " + response.MD5Hash +
            //    ", MD5HashTruncated: " + response.MD5Hash.Substring(0, 20) +
            //    ", AuthCode: " + response.AuthorizationCode +
            //    ", Approved: " + response.Approved +
            //    ", TransactionID: " + response.TransactionID +
            //    ", CreditCard: " + response.CardNumber +
            //    ", User ID: " + post.Get("x_cust_id") +
            //    ", Num_Judgment(s): " + post.Get("num_judgment");
            //return View();

            //if it's not valid - just send them to the home page. Don't throw - that's how hackers figure out what's wrong :)
            if (!isValid)
                return Redirect("/");
            else
            {
                string returnUrl = "";
                if (response.Approved)
                {
                    //get previously created invoice record and update with the correct judgments purchased
                    //JudgmentDB db = new JudgmentDB();
                    //int userID = Convert.ToInt32(post.Get("x_cust_id"));
                    //var invoice = (
                    //    from i in db.UserProfileJudgments
                    //    where i.UserId == userID && i.JudgmentCount == 0
                    //    select i).Single();
                    //invoice.JudgmentCount = Convert.ToInt32(post.Get("num_judgment"));
                    //db.SaveChanges();

                    returnUrl = ConfigurationManager.AppSettings["AuthorizeReturnURL"] + "Commerce/Success?n=" + post.Get("num_judgment") + "&i=" + post.Get("x_cust_id") + "&m=" + response.Message;
                }
                else
                {
                    returnUrl = ConfigurationManager.AppSettings["AuthorizeReturnURL"] + "Commerce/Failure?m=" + response.Message;
                }
                
                //the URL to redirect to- this MUST be absolute
                return Content(AuthorizeNet.Helpers.CheckoutFormBuilders.Redirecter(returnUrl));
            }
        }


        public ActionResult Success()
        {
            try
            {
                ViewBag.Message = Request.QueryString["m"];
                int userID = Convert.ToInt32(Request.QueryString["i"]);
                int numJudgments = Convert.ToInt32(Request.QueryString["n"]);

                JudgmentDB db = new JudgmentDB();
                var invoice = (
                    from i in db.UserProfileJudgments
                    where i.UserId == userID && i.JudgmentCount == 0
                    select i);
                List<UserProfileJudgment> userProfileJudgmentList = invoice.ToList();

                int index = 0;
                int count = userProfileJudgmentList.Count();
                foreach (UserProfileJudgment upg in userProfileJudgmentList)
                {
                    if (index + 1 < count)
                        DeleteInvoice(upg.invoice);
                    else
                        UpdateInvoice(upg.invoice, numJudgments);
                    index++;
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Error saving success data";
                return View();
            }
        }


        public ActionResult Failure()
        {
            ViewBag.Message = Request.QueryString["m"];
            return View();
        }



    }
}

Judgmentrac/Controllers/JudgmentController.cs
using Judgmentrac.Models;
using Judgmentrac.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;


namespace Judgmentrac.Controllers
{
    [Authorize]        
    public class JudgmentController : SuperController
    {
        private JudgmentDB db = new JudgmentDB();


        // GET: /Judgment/
        public ActionResult Index(string sortOrder)
        {
            // do we have an error in the query string?
            //string error = this.Request.QueryString["err"];
            //if (error != "") ViewBag.ErrorMessage = error;

            // viewbag sort variables
            ViewBag.NameSortParm = sortOrder == "Name" ? "Name desc" : "Name";
            ViewBag.StartSortParm = sortOrder == "Start" ? "Start desc" : "Start";
            ViewBag.EndSortParm = sortOrder == "End" ? "End desc" : "End";

            IEnumerable<Dispute> disputeList = GetJudgmentsByUserId(WebSecurity.CurrentUserId);
            
            // create an instance of view model DisputeViewModel so we can take advantage of computed properties (not stored in DB)
            List<DisputeViewModel> disputeViewList = new List<DisputeViewModel>();
            foreach (Dispute dispute in disputeList)
                disputeViewList.Add(new DisputeViewModel(dispute));

            // sort
            switch (sortOrder)
            {
                case "Name":
                    disputeViewList = disputeViewList.OrderBy(s => s.Dispute.Name).ToList();
                    break;
                case "Name desc":
                    disputeViewList = disputeViewList.OrderByDescending(s => s.Dispute.Name).ToList();
                    break;
                case "Start":
                    disputeViewList = disputeViewList.OrderBy(s => s.Dispute.StartDate).ToList();
                    break;
                case "Start desc":
                    disputeViewList = disputeViewList.OrderByDescending(s => s.Dispute.StartDate).ToList();
                    break;
                case "End":
                    disputeViewList = disputeViewList.OrderBy(s => s.Dispute.EndDate).ToList();
                    break;
                case "End desc":
                    disputeViewList = disputeViewList.OrderByDescending(s => s.Dispute.EndDate).ToList();
                    break;
            }

            ViewBag.JudgmentCount = GetJudgmentCount();
            return View(disputeViewList);
        }

       
        // GET: /Judgment/Create
        public ActionResult Create()
        {
            if (WebSecurity.IsAuthenticated)
            {
                int judgmentCount = GetJudgmentCount();
                if (judgmentCount > 0)
                {
                    ViewBag.JudgmentCount = judgmentCount;
                    return View("Create");
                }
                else
                    return View("NoJudgment");
            }
            else
            {
                return View("NoJudgment");
            }
        }


        // POST: /Judgement/Create
        [HttpPost]
        public ActionResult Create(Dispute disputeInput)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var judgment = new JudgmentDB())
                    {
                        var dispute = new Dispute
                        {
                            Name = disputeInput.Name,
                            Principal = disputeInput.Principal,
                            Rate = disputeInput.Rate,
                            StartDate = disputeInput.StartDate,
                            EndDate = disputeInput.EndDate,
                            UserId = WebSecurity.CurrentUserId,
                            IsActive = true
                        };

                        judgment.Disputes.Add(dispute);
                        judgment.SaveChanges();
                    }

                    return RedirectToAction("Index", new { Message = "Judgment Successfully Created" });
                }
                else
                {
                    ViewBag.ErrorMsg = "Error on form, please fix and resubmit";
                    return View();
                }
            }
            catch
            {
                ViewBag.ErrorMsg = "Error adding judgment, please try again.";
                return View();
            }
        }


        // POST: /Judgment/Delete/5
        [HttpPost]
        public bool Delete(int id)
        {
            try
            {
                Dispute dispute = db.Disputes.Find(id);
                dispute.IsActive = false;
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Judgmentrac/Views/Judgment/Create.cshtml
@model Judgmentrac.Models.Dispute

@{
    ViewBag.Title = "Create a New Judgment";
}
<div class="container" id="payment-container">
    <div id="paymentForm">
        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
        </hgroup>
        
        <p>
            You have <b>@ViewBag.JudgmentCount</b> judgment(s) available to create
            <br /><br />
        </p>

        <div class="errorMsg">
            @ViewBag.ErrorMsg
        </div>

        @using (Html.BeginForm()) {
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Judgment</legend>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Principal)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Principal)
                    @Html.ValidationMessageFor(model => model.Principal)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Rate)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Rate)
                    @Html.ValidationMessageFor(model => model.Rate)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.StartDate)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.StartDate)
                    @Html.ValidationMessageFor(model => model.StartDate)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.EndDate)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.EndDate)
                    @Html.ValidationMessageFor(model => model.EndDate)
                </div>

                <p>
                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Cancel", "Index", "Judgment", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" }) 
                </p>
            </fieldset>
        }
    </div>
</div>

@section Scripts {
<script type="text/javascript">
    $(function () {
        $("#StartDate").datepicker();
        $("#EndDate").datepicker();
    });
</script>
}

Judgmentrac/Views/Judgment/Index.cshtml
@model IEnumerable<Judgmentrac.ViewModels.DisputeViewModel>

@{
    ViewBag.Title = "My Judgments";
}

@{
    var grid = new WebGrid(Model,
        defaultSort:"Name", 
        columnNames:new[]{"Name","Principal","Rate","StartDate"},
        ajaxUpdateContainerId: "grid"
    );
}
<div class="section">
    <div class="container title-section">
        <div class="pull-left">
            <h4>@User.Identity.Name, you have @ViewBag.JudgmentCount judgments available for use</h4>
        </div>
        <div class="pull-right">
            @Html.ActionLink("Purchase Judgments", "Index", "Commerce", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-medium" })
            @Html.ActionLink("Create Judgment", "Create", "Judgment", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-medium" })    
        </div>
    </div>
    <div class="table-header-section">
        <div class="container">
            <table class="header-table table">
                <thead>
                    <tr class="webgrid-header">
                            <th class="expand"></th>
                            <th class="dispute-name">@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm })</th>
                            <th>Principal</th>
                            <th>Rate</th>
                            <th>Interest</th>
                            <th>Due</th>
                            <th>@Html.ActionLink("Start", "Index", new { sortOrder = ViewBag.StartSortParm })</th>
                            <th>@Html.ActionLink("End", "Index", new { sortOrder = ViewBag.EndSortParm })</th>
                            <th>Payments</th>
                            <th></th>
                    </tr>
                </thead>
             </table>
        </div>
    </div>
    <div class="container">
        <div class="errorMsg">@ViewBag.ErrorMessage</div>
        <table class="main-table table">
            <thead>
                <tr>
                    <th class="expand"></th>
                    <th class="dispute-name"></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var disputeView in Model)
            {
                <tr class="dispute-parent-row">
                    <td class="expand">
                        <i class="icon-chevron-right"></i>
                        <i class="icon-chevron-down" style="display:none"></i>
                    </td>
                    <td class="dispute-name">
                        @Html.Hidden("disputeID", @disputeView.Dispute.ID)
                        @disputeView.Dispute.Name
                    </td>
                    <td>$@disputeView.Dispute.Principal</td>
                    <td>@disputeView.Dispute.Rate%</td>
                    <td>$@Math.Round(disputeView.InterestTotal, 2)</td>
                    <td>$@Math.Round(disputeView.Dispute.Principal - disputeView.PaymentTotal + disputeView.InterestTotal, 2)</td>
                    <td>@disputeView.Dispute.StartDate.ToString("d")</td>
                    <td>@disputeView.Dispute.EndDate.ToString("d")</td>
                    <td>@disputeView.Dispute.Payments.Count</td>
                    <td><i class="icon-trash"></i></td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
<script type="text/javascript">
    // handle row click
    $(".main-table tr.dispute-parent-row").live('click', function () {
        var $this = $(this)

        // remove any error message if it exists
        var errorRow = $('.main-table tr.error-row');
        if (errorRow.length) errorRow.remove();

        // Table row handler - open / close payments
        if ($this.next()[0] === $('.payments')[0] && $('.payments').length) {
            closePayments($('.payments'));
        }
        else {
            closePayments($('.payments'));
            var popDown = $('<tr class="payments" />').load('/Payment/PartialDetails/' + $this.find('#disputeID').val());
            $this.after(popDown);

            // toggle chevron icons
            var previousRow = popDown.prev('tr');
            previousRow.find('i.icon-chevron-right').hide();
            previousRow.find('i.icon-chevron-down').show();
        }

        // toggle expand arrow
        //$this.find(".expand i").toggle();
    });

    // Close (remove) payments
    var closePayments = function (node) {
        // toggle chevron icons
        var previousRow = node.prev('tr');
        previousRow.find('i.icon-chevron-down').hide();
        previousRow.find('i.icon-chevron-right').show();

        node.closest('tr.payments').remove();
    };

    // user is attempting to delete judgment
    $('tr.dispute-parent-row td .icon-trash').live('click', function (event) {
        event.stopPropagation();
        var answer = confirm("Are you sure you want to delete this Judgment?")
        if (answer) {
            closePayments($('.payments'));
            var disputeRow = $(this).closest('tr');
            var disputeID = disputeRow.find('input#disputeID').val();
            $.ajax({
                type: "POST",
                url: "/Judgment/Delete/" + disputeID,
                success: function (data) {
                    if (data == "True") {
                        disputeRow.remove();
                    } else {
                        disputeRow.after("<tr class='error-row'><td colspan='10'><div class='errorMsg' style='text-align:center'>Error attempting to remove Judgment, please try again</div></td></tr>");
                    }
                },
                error: function (data) {
                    disputeRow.after("<tr class='error-row'><td colspan='10'><div class='errorMsg' style='text-align:center'>Error attempting to remove Judgment, please try again</div></td></tr>");
                }
            });
        }
    });

    // user is trying to delete a judgment payment
    $('tr.payments i.icon-trash').live('click', function (event) {
        event.stopPropagation();
        var answer = confirm("Are you sure you want to delete this payment?");
        if (answer) {
            var paymentRow = $(this).closest('tr');
            var paymentID = paymentRow.find('input#paymentID').val();
            $.ajax({
                type: "POST",
                url: "/Payment/Delete/" + paymentID,
                success: function (data) {
                    if (data == "True") {
                        paymentRow.remove();
                    }
                } //,
                //error: function (data) {
                //    console.log("failure payment delete");
                //}
            });
        }
    });
</script>       
}

Judgmentrac/Views/Judgment/NoJudgment.cshtml
@{
    ViewBag.Title = "No Judgments Available";
}

<div class="container" id="payment-container">
    <div id="paymentForm">
        
        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
        </hgroup>
        
        <p>You do not have any judgments available at this time, please click the button below to purchase </p>
        <p>@Html.ActionLink("Purchase Judgment", "Index", "Commerce", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })</p>
    
    </div>
</div>